param(
    [Parameter(Mandatory = $true)][string]$SvgPath,
    [Parameter(Mandatory = $true)][string]$OutputPath
)

$ErrorActionPreference = "Stop"
Import-Module (Join-Path $PSScriptRoot "superzip_brand_logo.psm1") -Force

# Purpose: Format a floating-point value as a C++ float literal.
# Inputs: `Value` is a geometry coordinate from the canonical SVG.
# Outputs: Returns an invariant-culture literal with an `F` suffix.
function Format-CppFloatLiteral {
    param([Parameter(Mandatory = $true)][double]$Value)

    return ($Value.ToString("0.0#####", [Globalization.CultureInfo]::InvariantCulture) + "F")
}

$mark = Read-SuperZipLogoMark -SvgPath $SvgPath
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputPath) | Out-Null

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Generated from resources/brand/superzip-logo.svg by tools/generate_brand_logo_header.ps1.")
$lines.Add("// Do not edit this file directly; update the canonical SVG and regenerate.")
$lines.Add("#pragma once")
$lines.Add("")
$lines.Add("#include <array>")
$lines.Add("")
$lines.Add("namespace superzip::brand {")
$lines.Add("")
$lines.Add("struct LogoPoint {")
$lines.Add("    float x;")
$lines.Add("    float y;")
$lines.Add("};")
$lines.Add("")
$lines.Add("struct LogoLayer {")
$lines.Add("    std::array<LogoPoint, 4> points;")
$lines.Add("};")
$lines.Add("")
$lines.Add("inline constexpr float kSuperZipLogoMarkWidth = $(Format-CppFloatLiteral -Value $mark.Width);")
$lines.Add("inline constexpr float kSuperZipLogoMarkHeight = $(Format-CppFloatLiteral -Value $mark.Height);")
$lines.Add("inline constexpr float kSuperZipLogoMarkStrokeWidth = $(Format-CppFloatLiteral -Value $mark.StrokeWidth);")
$lines.Add("inline constexpr std::array<LogoLayer, 3> kSuperZipLogoMarkLayers{{")
foreach ($layer in $mark.Layers) {
    $pointLiterals = foreach ($point in $layer.Points) {
        "LogoPoint{$(Format-CppFloatLiteral -Value $point.X), $(Format-CppFloatLiteral -Value $point.Y)}"
    }
    $lines.Add("    LogoLayer{{{ $($pointLiterals -join ', ') }}},")
}
$lines.Add("}};")
$lines.Add("")
$lines.Add("}  // namespace superzip::brand")
$lines.Add("")
[IO.File]::WriteAllLines($OutputPath, $lines.ToArray(), [Text.UTF8Encoding]::new($false))
