# Purpose: Recognize exact complete dictionary revisions of their preceding
# patch. Inputs: Full actual/preceding hashes. Outputs: Only known identity
# pairs match.
function(superzip_zstd_dictionary_patch_is_superseded actual preceding output)
  set(recognized FALSE)
  foreach(part IN ITEMS cover fastcover header)
    set(key "_zstd_dictionary_bounds_${part}")
    if(actual STREQUAL "${${key}_patched}" AND preceding STREQUAL
                                               "${${key}_original}")
      set(recognized TRUE)
    endif()
  endforeach()
  set(${output}
      ${recognized}
      PARENT_SCOPE)
endfunction()

# Purpose: Publish exact dictionary caller and ownership boundary revisions.
# Inputs: source_dir owns known generated bytes; provenance remains immutable.
# Outputs: Migrates both builders and declarations; rejects drift, is
# idempotent.
function(superzip_patch_zstd_dictionary_bounds source_dir)
  foreach(part IN ITEMS cover fastcover header)
    set(key "_zstd_dictionary_bounds_${part}")
    set(source "${source_dir}/lib/dictBuilder/${${key}_file}")
    file(SHA256 "${source}" actual_hash)
    if(actual_hash STREQUAL "${${key}_patched}")
      continue()
    endif()
    if(NOT actual_hash STREQUAL "${${key}_original}")
      message(FATAL_ERROR "Zstandard patch source identity mismatch: ${source}")
    endif()
    file(READ "${source}" content)
    if(part STREQUAL header)
      string(REPLACE "typedef struct COVER_dictSelection {"
                     "${_zstd_bounds_header_type}" content "${content}")
      string(REPLACE "} COVER_dictSelection_t;" "${_zstd_bounds_header_bridge}"
                     content "${content}")
      string(REPLACE "${_zstd_bounds_call_0}" "${_zstd_bounds_call_1}" content
                     "${content}")
    else()
      string(REPLACE "${_zstd_bounds_call_2}" "${_zstd_bounds_call_3}" content
                     "${content}")
      if(part STREQUAL cover)
        string(REPLACE "free(selection.dictContent);"
                       "COVER_freeSelectedDictionary(selection.dictContent);"
                       content "${content}")
      endif()
    endif()
    superzip_write_verified_zstd_patch("${source}" "${actual_hash}"
                                       "${${key}_patched}" "${content}")
  endforeach()
endfunction()

string(
  CONCAT _zstd_bounds_header_type
         "/* One allocation and its initialized suffix; "
         "output capacity is independent. */\n"
         "typedef struct {\n"
         "  const BYTE* data;\n"
         "  size_t capacity;\n"
         "  size_t initializedOffset;\n"
         "} COVER_dictContent_t;\n\n"
         "typedef struct COVER_dictSelection {")
string(
  CONCAT _zstd_bounds_header_bridge
         "} COVER_dictSelection_t;\n\n"
         "/* Private C/C++ bridge; transferred arrays require "
         "the matching release. */\n"
         "COVER_dictSelection_t COVER_selectDictOwned("
         "COVER_dictContent_t content, size_t dictBufferCapacity,\n"
         "    const BYTE* samplesBuffer, const size_t* samplesSizes, "
         "unsigned nbFinalizeSamples,\n"
         "    size_t nbCheckSamples, size_t nbSamples, "
         "ZDICT_cover_params_t params, size_t* offsets, "
         "size_t totalCompressedSize);\n"
         "void COVER_freeSelectedDictionary(BYTE* data);")
string(
  CONCAT
    _zstd_bounds_call_0
    "COVER_selectDict(BYTE* customDictContent, size_t dictBufferCapacity,\n"
    "                       size_t dictContentSize,")
string(CONCAT _zstd_bounds_call_1
              "COVER_selectDict(COVER_dictContent_t content, "
              "size_t dictBufferCapacity,")
string(CONCAT _zstd_bounds_call_2
              "selection = COVER_selectDict(dict + tail, dictBufferCapacity, "
              "dictBufferCapacity - tail,")
string(
  CONCAT
    _zstd_bounds_call_3
    "const COVER_dictContent_t content = {dict, dictBufferCapacity, tail};\n"
    "    selection = COVER_selectDict(content, dictBufferCapacity,")

set(_zstd_dictionary_bounds_cover_file "cover.c")
set(_zstd_dictionary_bounds_cover_original
    "fe6ea20bb307208825aff536dc3a1467b9961cb6caede2f1cd4308813667d867")
set(_zstd_dictionary_bounds_cover_patched
    "2c99b6e65bf7d999920d20206efe9dffdd86bc1c3fac2cfdbccf187487b1a17e")
set(_zstd_dictionary_bounds_fastcover_file "fastcover.c")
set(_zstd_dictionary_bounds_fastcover_original
    "0b8b511e6370e89cb257d1a4b4d8e77add5537ffb999cfe5e7e59e454c93f38f")
set(_zstd_dictionary_bounds_fastcover_patched
    "ae43f56fd892fe02ce5fe048980a2ae2c63eadc6e70b8e3662fe56d08275e085")
set(_zstd_dictionary_bounds_header_file "cover.h")
set(_zstd_dictionary_bounds_header_original
    "432323ee0a02dbfb49abb146137fc152142df20b4223e1a8a5f6f6303a8eeed5")
set(_zstd_dictionary_bounds_header_patched
    "cb1b1c2c244ad69d250fda6422c2479baf340dff2ddd63d6c99bb187d642e34b")
